enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/webos-ext",
	"App.css",
	"App.js",
	"Main.js",
	"ItemList.js",
	"Product.js",
	"DesiredProduct.js",
	"Storage.js",
	"ResizableDrawer.js",
	"Location.js",
	"CheckoutHelper.js",
	"UnavailableItemList.js",
	"CheckoutButton.js",
	"Divider.js",
	"SubMenu.js"
);
