enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/webos-ext",
	"App.css",
	"App.js",
	"Main.js",
	"ItemList.js",
	"Product.js",
	"DesiredProduct.js",
	//"ProductDisplay.js",
	"Storage.js",
	"ResizableDrawer.js"
);
